### ISSUE TITLE
Potential Installation Issue

### ISSUE THREAD

**Issue by zachlevin** [benjann/colrspace#5]
Hello,

When installing this package manually (due to firewall issues) I have encountered the following issue I cannot seem to debug:
class ColrSpace undefined
(error occurred while loading colorpalette.ado)

Testing this on a different computer I do not seem to have the issue. I was hoping you might have suggestions of why this error might be occurring. 

Thank you!

**Comment by benjann** [comment]
Hi, file `lcolrspace.mlib` must be available to Stata. That is, make sure to store the file somewhere along the ado path (type `adopath`, also see `help sysdir`). If you type `mata mata mlib index` in Stata, `lcolrspace` should be listed among the available libraries, otherwise the colrspace functions will not be available. Furthermore, also make sure that all library files are somewhere in the adopath; these files contain the color definitions.

**Comment by zachlevin** [comment]
Thank you. It just started working - I am not sure why, but I think adding a path directly to the lcolrspace.mlb file may have helped!
